setup-melange - make bwrap work on ubuntu with user namespaces.

diff --git a/setup-melange/action.yaml b/setup-melange/action.yaml
--- a/setup-melange/action.yaml
+++ b/setup-melange/action.yaml
@@ -33,6 +33,35 @@ runs:
       run: |
         sudo apt install --assume-yes bubblewrap
 
+    - name: Enable bubblewrap in ubuntu
+      shell: bash
+      run: |
+        set -x
+        # https://github.com/chainguard-dev/melange/issues/1508
+        sudo tee /etc/apparmor.d/local-bwrap <<"EOF"
+        abi <abi/4.0>,
+        include <tunables/global>
+
+        profile local-bwrap /usr/bin/bwrap flags=(unconfined) {
+          userns,
+          # Site-specific additions and overrides. See local/README for details.
+          include if exists <local/bwrap>
+        }
+        EOF
+
+        sudo systemctl reload apparmor
+        if ! bwrap --unshare-user --bind / / true ; then
+          echo "FATAL: failed to verify 'bwrap --unshare-user'"
+          which bwrap || :
+          ls /proc/self/ns || echo "no /proc/self/ns"
+          kver=$(uname -r) || echo "uname -r failed"
+          if config="/boot/config-$kver" && [ -f "$config" ]; then
+            grep CONFIG_USER_NS "$config" || echo "no CONFIG_USER_NS in $config"
+          fi
+          exit 1
+        fi
+        echo "bubblewrap (bwrap) installed successfully."
+
     - name: 'Install melange'
       if:
       shell: bash
